### ISSUE TITLE
Improve searching to avoid inadvertent porn matches

### ISSUE THREAD

**Issue by funkypenguin** [sleeyax/stremio-easynews-addon#17]
I did an initial test and quickly discovered porn being returned for some searches. Try searching for https://www.imdb.com/title/tt29259099/ 😮

**Comment by sleeyax** [comment]
Turns out there's a preference that can be enabled in your Easynews account settings:

![image](https://github.com/user-attachments/assets/90ed8ce6-a804-4567-bb28-dd74eba3103c)

Unfortunately it doesn't help much.

**Comment by sleeyax** [comment]
Should be improved in https://github.com/sleeyax/stremio-easynews-addon/releases/tag/v1.3.0.  Keep in mind that the search catalog could still return NSFW results because it matches titles in a not so strict manner.

I'm closing this as solved, but please let me know if you still manage to find unwanted results for regular titles and we'll reopen this issue.

**Comment by funkypenguin** [comment]
Tested, results are much better, no more unexpected surprises! :)
