### ISSUE TITLE
Movie not showing up in the addon

### ISSUE THREAD

**Issue by znre** [sleeyax/stremio-easynews-addon#38]
Mad Max: Fury Road is not returning any results.

Just wanted to add some other movies (I confirmed that they are showing in the old EN addon):
- Three Colors: Blue (1993)
- Willy Wonka and the Chocolate Factory (1973)
- WALL-E (2008)
- Mission: Impossible - Dead Reckoning Part One (2023)
- The Lord of the Rings: The Fellowship of the Ring
- Once Upon a Time in Hollywood

**Comment by sleeyax** [comment]
An overview of issues found with these titles:

- > Three Colors: Blue (1993)

  Sanitization issue of  `:` character. 

- > Willy Wonka and the Chocolate Factory (1973)

  Mismatch between `&` symbol and the literal word `and`

- > WALL-E (2008)

  The actual title contains an annoying dot: `WALL·E`. Should be converted to a `-`, but we convert that to a space. Won't fix this because easynews doesn't provide this title anyways. If needed, try the search catalog.

- > Mission: Impossible - Dead Reckoning Part One (2023)
 
  Cinemeta names this title just 'dead reckoning', making it impossible (pun not intended) to match properly because we match movies strictly by their full title. Won't fix this either, use the search catalog to watch this content.

- > The Lord of the Rings: The Fellowship of the Ring

  Sanitization issue of  `:` character. 

- > Once Upon a Time in Hollywood

  Cinemeta provides this title as `Once Upon a Time ... in Hollywood`. So this is a sanitization issue with the `.` character.
